config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#show'

  mount GoodJob::Engine => 'good_job'

  resource :sessions, only: %i[new create destroy]
  get '/sessions' => redirect('/sessions/new')

  resources :password_resets, only: %i[new create edit update]

  resource :settings, only: %i[edit update]
  resolve('Setting') { [:settings] }

  resource :companies, only: %i[new create edit update]
  resolve('Company') { [:companies] }

  resources :users, only: %i[new create]

  namespace :me do
    resource :profile, only: %i[show edit update]
  end

  resources :customers do
    member do
      delete :archive
    end

    collection do
      get :daily
    end
  end
  resources :vehicles

  resources :places do
    collection do
      get :daily
    end
  end

  resources :transporters do
    collection do
      get :daily
    end
    scope module: :transporters do
      resources :absences, except: %i[index show]
    end
  end

  resources :daily_quests, only: %i[index show destroy] do
    member do
      post :reset
      post :duplicate_week
      post 'optimize'
    end

    scope module: :daily_quests do
      resources :missions

      resources :steps, only: %i[edit update destroy] do
        member do
          post 'optimize'
        end
      end

      resources :transporters, only: [] do
        collection do
          post :send_all_plannings
        end

        member do
          post :send_planning
        end

        scope module: :transporters do
          resources :steps, only: %i[index]
        end
      end

      resources :missions, only: [] do
        scope module: :missions do
          resources :steps, only: %i[index update]
        end
      end
    end
  end

  namespace :addresses do
    resource :search, only: :show
  end
end

app/models/daily_quest.rb
class DailyQuest < ApplicationRecord
  WAITING_TIME = 30.minutes # time before hiding steps

  enum status: { not_started: 0, pending: 1, ended: 2 }, _default: :not_started

  belongs_to :company
  has_many :missions, dependent: :destroy
  has_many :steps, through: :missions

  validates :started_on, presence: true

  accepts_nested_attributes_for :missions, reject_if: :all_blank, allow_destroy: true

  def self.clone_week!(using:)
    my_week = using.company
                   .daily_quests
                   .joins(:missions)
                   .where(started_on: (using.started_on.beginning_of_week)..(using.started_on.end_of_week))

    my_week.each do |daily|
      started_on = daily.started_on.in(1.week)
      my_daily_quest = daily.company.daily_quests.find_or_create_by(
        started_on: started_on
      )
      my_daily_quest.save!

      Rails.logger.debug my_daily_quest.inspect

      my_daily_quest.missions.delete_all
      daily.missions.each do |mission|
        my_mission = mission.dup
        my_mission.drop_duration_hours = mission.drop_duration / 60
        my_mission.drop_duration_minutes = mission.drop_duration % 60
        my_mission.daily_quest_id = my_daily_quest.id
        my_mission.save!
        Rails.logger.debug my_mission.inspect
      end
    end
  end

  def title
    I18n.l(started_on)
  end

  def recompute_missions_position
    missions.order(drop_time: :asc).each_with_index do |mission, index|
      mission.update_column :position, index + 1
    end
  end

  # def recompute_steps_position
  # missions.map(&:steps).flatten
  # end
end

# == Schema Information
#
# Table name: daily_quests
#
#  id         :bigint(8)        not null, primary key
#  started_on :date
#  status     :integer          default("not_started"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  company_id :bigint(8)
#
# Indexes
#
#  index_daily_quests_on_company_id  (company_id)
#

app/controllers/daily_quests/missions/steps_controller.rb
module DailyQuests
  module Missions
    class StepsController < ApplicationController
      before_action :set_daily_quest
      before_action :set_mission
      before_action :set_step, only: :update

      # @route GET /daily_quests/:daily_quest_id/missions/:mission_id/steps (daily_quest_mission_steps)
      def index
        authorize! Step, context: { daily_quest: @daily_quest }

        @steps = @mission.steps.all
      end

      # @route PATCH /daily_quests/:daily_quest_id/missions/:mission_id/steps/:id (daily_quest_mission_step)
      # @route PUT /daily_quests/:daily_quest_id/missions/:mission_id/steps/:id (daily_quest_mission_step)
      def update
        authorize! @step, context: { daily_quest: @daily_quest }

        return if @step.update(step_params)

        head :unprocessable_entity
      end

      private

      def set_daily_quest
        @daily_quest = company.daily_quests.find(params[:daily_quest_id])
      end

      def set_mission
        @mission = @daily_quest.missions.find(params[:mission_id])
      end

      def set_step
        @step = @daily_quest.steps.find(params[:id])
      end

      def step_params
        params.require(:step).permit(:transporter_id)
      end
    end
  end
end

app/controllers/daily_quests/missions_controller.rb
module DailyQuests
  class MissionsController < ApplicationController
    before_action :set_daily_quest
    before_action :set_mission, only: %i[show edit update destroy]

    # @route GET /daily_quests/:daily_quest_id/missions (daily_quest_missions)
    def index
      authorize! Mission, context: { daily_quest: @daily_quest }

      if params[:date].present?
        set_daily_quest_by_date
      else
        set_daily_quest
      end

      @missions = @daily_quest.missions
    end

    # @route GET /daily_quests/:daily_quest_id/missions/new (new_daily_quest_mission)
    def new
      authorize! Mission, context: { daily_quest: @daily_quest }

      @mission = @daily_quest.missions.new
    end

    # @route POST /daily_quests/:daily_quest_id/missions (daily_quest_missions)
    def create
      authorize! Mission, context: { daily_quest: @daily_quest }

      @mission = @daily_quest.missions.new(mission_params)

      respond_to do |format|
        if @mission.save
          notice = 'La mission a bien été créé.'

          format.html { redirect_to daily_quest_missions_path(@daily_quest), notice: notice }
          format.turbo_stream { flash.now[:notice] = notice }
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    # @route GET /daily_quests/:daily_quest_id/missions/:id (daily_quest_mission)
    def show
      authorize! @mission, context: { daily_quest: @mission.daily_quest }
    end

    # @route GET /daily_quests/:daily_quest_id/missions/:id/edit (edit_daily_quest_mission)
    def edit
      authorize! @mission, context: { daily_quest: @mission.daily_quest }
    end

    # @route PATCH /daily_quests/:daily_quest_id/missions/:id (daily_quest_mission)
    # @route PUT /daily_quests/:daily_quest_id/missions/:id (daily_quest_mission)
    def update
      authorize! @mission, context: { daily_quest: @mission.daily_quest }

      if @mission.update(mission_params)
        redirect_to daily_quest_mission_path(@daily_quest, @mission), notice: 'La mission a bien été mise à jour.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # @route DELETE /daily_quests/:daily_quest_id/missions/:id (daily_quest_mission)
    def destroy
      authorize! @mission, context: { daily_quest: @mission.daily_quest }

      @mission.destroy

      respond_to do |format|
        notice = 'La mission a bien été supprimée'

        format.html { redirect_to daily_quest_missions_path(date: @daily_quest.started_on), notice: notice }
        format.turbo_stream { flash.now[:notice] = notice }
      end
    end

    private

    def mission_params
      params.require(:mission).permit(
        :drop_time, :round_trip, :drop_duration_hours,
        :drop_duration_minutes, :customer_id, :place_id
      )
    end

    def set_daily_quest
      @daily_quest = company.daily_quests.find(params[:daily_quest_id])
    end

    def set_daily_quest_by_date
      @daily_quest = company.daily_quests.find_or_create_by(started_on: date)

      redirect_to daily_quest_missions_path(@daily_quest)
    end

    def set_mission
      @mission = @daily_quest.missions.find(params[:id])
    end

    def date
      if params[:date].present?
        begin
          Date.parse(params[:date])
        rescue StandardError
          Date.current
        end
      else
        Date.current
      end
    end
  end
end

app/controllers/daily_quests/steps_controller.rb
module DailyQuests
  class StepsController < ApplicationController
    before_action :set_daily_quest
    before_action :set_step

    # @route GET /daily_quests/:daily_quest_id/steps/:id/edit (edit_daily_quest_step)
    def edit
      authorize! @step, context: { daily_quest: @daily_quest }
    end

    # @route PATCH /daily_quests/:daily_quest_id/steps/:id (daily_quest_step)
    # @route PUT /daily_quests/:daily_quest_id/steps/:id (daily_quest_step)
    def update
      authorize! @step, context: { daily_quest: @daily_quest }

      if @step.update(step_params)
        render partial: 'daily_quests/step', locals: { step: @step }
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # @route DELETE /daily_quests/:daily_quest_id/steps/:id (daily_quest_step)
    def destroy
      authorize! @step, context: { daily_quest: @daily_quest }

      @step.destroy

      respond_to do |format|
        notice = 'La mission a bien été supprimée'

        format.html { redirect_to daily_quests_path(date: @daily_quest.started_on), notice: notice }
        format.turbo_stream { flash.now[:notice] = notice }
      end
    end

    # @route POST /daily_quests/:daily_quest_id/steps/:id/optimize (optimize_daily_quest_step)
    def optimize
      authorize! @step, context: { daily_quest: @daily_quest }

      Optimizer.call(@step)

      redirect_to daily_quests_path(date: @daily_quest.started_on)
    end

    private

    def step_params
      params.require(:step).permit(:description)
    end

    def set_daily_quest
      @daily_quest = company.daily_quests.find(params[:daily_quest_id])
    end

    def set_step
      @step = @daily_quest.steps.find(params[:id])
    end
  end
end

app/controllers/daily_quests/transporters/steps_controller.rb
module DailyQuests
  module Transporters
    class StepsController < ApplicationController
      before_action :set_daily_quest
      before_action :set_transporter

      # @route GET /daily_quests/:daily_quest_id/transporters/:transporter_id/steps (daily_quest_transporter_steps)
      def index
        authorize! @transporter,
                   with: DailyQuests::Transporters::StepPolicy,
                   context: { daily_quest: @daily_quest }

        @steps = @daily_quest.steps.with_all_rich_text.where(transporter: @transporter)

        respond_to do |format|
          format.html
          format.pdf do
            name = "#{@daily_quest.started_on} - #{@transporter.full_name}".parameterize(separator: '_')

            render pdf: name
          end
        end
      end

      private

      def set_daily_quest
        @daily_quest = company.daily_quests.find(params[:daily_quest_id])
      end

      def set_transporter
        @transporter = company.transporters.find(params[:transporter_id])
      end
    end
  end
end

app/controllers/daily_quests/transporters_controller.rb
module DailyQuests
  class TransportersController < ApplicationController
    before_action :set_daily_quest
    before_action :set_transporter, only: :send_planning

    # @route POST /daily_quests/:daily_quest_id/transporters/send_all_plannings (send_all_plannings_daily_quest_transporters)
    def send_all_plannings
      authorize! Transporter, context: { daily_quest: @daily_quest }

      transporters = company.daily_quests.with_attached_photo.includes(:absences)
      transporters = transporters.reject do |transporter|
        transporter.off?(@daily_quest.started_on)
      end

      transporters.each do |transporter|
        TransporterMailer
          .with(transporter: transporter, daily_quest: @daily_quest)
          .send_planning
          .deliver_later
      end

      respond_to do |format|
        notice = "Les plannings du jour sont en train d'être envoyés aux différents chauffeurs"

        format.html do
          redirect_to daily_quest_path(date: @daily_quest.started_on), notice: notice
        end
        format.turbo_stream { flash.now[:notice] = notice }
      end
    end

    # @route POST /daily_quests/:daily_quest_id/transporters/:id/send_planning (send_planning_daily_quest_transporter)
    def send_planning
      authorize! @transporter, context: { daily_quest: @daily_quest }

      TransporterMailer
        .with(transporter: @transporter, daily_quest: @daily_quest)
        .send_planning
        .deliver_later

      respond_to do |format|
        notice = "Le planning a bien été envoyé par email à #{@transporter.full_name}"

        format.html do
          redirect_to daily_quest_path(date: @daily_quest.started_on), notice: notice
        end
        format.turbo_stream { flash.now[:notice] = notice }
      end
    end

    private

    def set_daily_quest
      @daily_quest = company.daily_quests.find(params[:daily_quest_id])
    end

    def set_transporter
      @transporter = company.transporters.find(params[:id])
    end
  end
end

app/controllers/daily_quests_controller.rb
class DailyQuestsController < ApplicationController
  MAX_HOUR = 18

  before_action :set_daily_quest, only: %i[
    show destroy
    optimize duplicate_week reset
  ]

  # @route GET /daily_quests (daily_quests)
  def index
    authorize! DailyQuest

    # Planning redirect to next business day if current day is not
    unless calendar.business_day?(date)
      next_business_day = calendar.next_business_day(date)
      redirect_to daily_quests_path(date: next_business_day)
      return
    end

    # Planning redirect to tomorrow if todays missions are ended
    if params[:date].blank? && Time.current.hour >= MAX_HOUR
      next_business_day = calendar.next_business_day(Date.current)
      redirect_to daily_quests_path(date: next_business_day)
      return
    end

    @daily_quest = company.daily_quests.find_or_create_by(started_on: date)

    transporters = authorized_scope(company.transporters.includes(:absences))
    @transporters = transporters.sort_by_courses_for(@daily_quest)
  end

  # @route GET /daily_quests/:id (daily_quest)
  def show
    authorize! @daily_quest

    @mission = if params[:currentMissionId].present?
      @daily_quest.missions.find(params[:currentMissionId])
    else
      @daily_quest.missions.first
    end
  end

  # @route DELETE /daily_quests/:id (daily_quest)
  def destroy
    authorize! @daily_quest

    @daily_quest.missions.destroy_all

    redirect_to daily_quests_path, notice: 'Toutes les missions du jour ont bien été supprimées'
  end

  # @route POST /daily_quests/:id/optimize (optimize_daily_quest)
  def optimize
    authorize! @daily_quest

    steps = @daily_quest.missions.map(&:steps).flatten.select(&:single?).compact

    OptimizerJob.perform_later(steps.map(&:id))

    head :ok
  end

  # @route POST /daily_quests/:id/duplicate_week (duplicate_week_daily_quest)
  def duplicate_week
    authorize! @daily_quest

    DuplicateWeekJob.perform_later(@daily_quest)

    redirect_to daily_quests_path(date: @daily_quest.started_on), notice: 'La semaine est en cours de duplication. Veuillez patienter, cela peut prendre quelques minutes. La page sera rafraîchie une fois la copie terminée'
  end

  # @route POST /daily_quests/:id/reset (reset_daily_quest)
  def reset
    authorize! @daily_quest

    ResetDailyQuest.call(@daily_quest)

    redirect_to daily_quests_path(date: @daily_quest.started_on), notice: 'Le planning du jour a bien été réinitialisé'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_daily_quest
    @daily_quest = company.daily_quests.find(params[:id])
  end

  def date
    if params[:date].present?
      begin
        Date.parse(params[:date])
      rescue StandardError
        Date.current
      end
    else
      Date.current
    end
  end
end

app/views/daily_quests/_menu.html.slim
.group.relative.z-40 tabindex="-1"
  button.btn-add.inline-flex.w-full.items-center.justify-center.font-medium.leading-5.focus-within:outline.focus-within:outline-2.focus-within:border-transparent.focus-within:outline-primary-color type="button" aria-haspopup="true"
    span Menu
    svg.ml-2.-mr-1.h-5.w-5[viewbox="0 0 20 20" fill="currentColor"]
      path[fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"]

  .invisible.origin-top-right.-translate-y-2.scale-95.transform.opacity-0.transition-all.duration-300.group-focus-within:visible.group-focus-within:translate-y-0.group-focus-within:scale-100.group-focus-within:opacity-100
    .absolute.right-0.mt-2.w-56.origin-top-right.divide-y.divide-gray-100.rounded-md.border.border-gray-200.bg-white.shadow-lg.outline-none.dark:bg-gray-700.dark:border-gray-600.dark:text-white role="menu"
      nav.flex.flex-col.divide-y.dark:divide-gray-600.text-sm
        - if allowed_to?(:index?, Mission, namespace: DailyQuests, context: { daily_quest: daily_quest })
          = link_to daily_quest_missions_path(daily_quest),
                    class: 'p-3 hover:bg-gray-100 dark:hover:bg-gray-600 transition-colors text-green-500' do
            <svg class="inline mr-2 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 5.757v8.486M5.757 10h8.486M19 10a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
            </svg>
            | Gérer les missions

        - if allowed_to?(:show?, daily_quest)
          = link_to daily_quest,
                    class: 'p-3 hover:bg-gray-100 dark:hover:bg-gray-600 transition-colors' do
            <svg class="inline mr-2 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 14">
              <g stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                <path d="M10 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
                <path d="M10 13c4.97 0 9-2.686 9-6s-4.03-6-9-6-9 2.686-9 6 4.03 6 9 6Z"/>
              </g>
            </svg>
            | Détails des missions

        - if allowed_to?(:send_all_plannings?, Transporter, namespace: DailyQuests, context: { daily_quest: daily_quest })
          = link_to send_all_plannings_daily_quest_transporters_path(daily_quest),
                    data: { turbo_method: :post, turbo_confirm: 'Voulez-vous envoyer les plannings du jour à tous les chauffeurs par email ?' },
                    class: 'p-3 hover:bg-gray-100 dark:hover:bg-gray-600 transition-colors' do
            <svg class="inline mr-2 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 16">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 2-8.4 7.05a1 1 0 0 1-1.2 0L1 2m18 0a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1m18 0v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2"/>
            </svg>
            | Envoyer les plannings de tous les chauffeurs par email

        - if allowed_to?(:duplicate_week?, daily_quest)
          = link_to duplicate_week_daily_quest_path(daily_quest),
                    class: 'p-3 hover:bg-gray-100 dark:hover:bg-gray-600 transition-colors',
                    data: { turbo_method: :post, turbo_confirm: "Voulez-vous dupliquer la semaine du #{l(daily_quest.started_on.beginning_of_week)} - #{l(daily_quest.started_on.end_of_week)} sur la semaine du #{l(daily_quest.started_on.beginning_of_week + 1.week)} - #{l(daily_quest.started_on.end_of_week + 1.week)} ? Si une des journées existe déjà, elle sera supprimée et remplacée par la journée correspondante de la semaine sélectionnée" } do
              <svg class="inline mr-2 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 20">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m7.708 2.292.706-.706A2 2 0 0 1 9.828 1h6.239A.97.97 0 0 1 17 2v12a.97.97 0 0 1-.933 1H15M6 5v4a1 1 0 0 1-1 1H1m11-4v12a.97.97 0 0 1-.933 1H1.933A.97.97 0 0 1 1 18V9.828a2 2 0 0 1 .586-1.414l2.828-2.828A2 2 0 0 1 5.828 5h5.239A.97.97 0 0 1 12 6Z"/>
              </svg>
              | Dupliquer toute la semaine

        - if allowed_to?(:reset?, daily_quest)
          = link_to reset_daily_quest_path(daily_quest),
                    data: { turbo_method: :post, turbo_confirm: 'Voulez-vous réinitialiser le planning du jour ? Toutes les missions se trouvant actuellement dans les colonnes des chauffeurs seront désassignées.' },
                    class: 'p-3 text-red-700 dark:text-red-400 hover:bg-gray-100 dark:hover:bg-gray-600 transition-colors' do
            <svg class="inline mr-2 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m13 7-6 6m0-6 6 6m6-3a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
            </svg>
            | Réinitialiser le planning

        - if allowed_to?(:destroy?, daily_quest)
          = link_to daily_quest_path(daily_quest),
                    data: { turbo_method: :delete, turbo_confirm: 'Voulez-vous supprimer toutes les missions du jour ? Attention, cette action est irréversible !' },
                    class: 'p-3 text-red-700 dark:text-red-400 hover:bg-gray-100 dark:hover:bg-gray-600 transition-colors' do
            <svg class="inline mr-2 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m13 7-6 6m0-6 6 6m6-3a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
            </svg>
            | Supprimer les missions du jour

app/views/daily_quests/_navigate_planning_days.html.slim
.flex.flex-row.items-center.gap-2
  = yield

  - previous_business_day = calendar.previous_business_day(@daily_quest.started_on)
  - next_business_day = calendar.next_business_day(@daily_quest.started_on)

  = link_to "<< #{l(previous_business_day)}", daily_quests_path(date: previous_business_day), class: 'btn-back', title: 'Jour ouvré précédent'
  = link_to "#{l(next_business_day)} >>", daily_quests_path(date: next_business_day), class: 'btn-back', title: 'Jour ouvré suivant'

app/views/daily_quests/_transporter_column.html.slim
.w-full.lg:flex-none.lg:w-1/3.lg:w-1/4.border-2.border-dashed.transition-colors.p-2.rounded-lg.hover:border-blue-600 class=("2xl:w-[#{percentage}%]" if options.big_screen_planning_show_all_transporters?) class=(transporter == current_user ? 'border-blue-500' : 'border-teal-500')
  header.flex.justify-between.text-center.bg-gray-700.text-white.rounded-t-lg.p-2.items-center
    .flex.items-center.gap-2
      - if transporter.photo.attached?
        = image_tag transporter.photo, class: 'w-10 rounded-full'
        .text-left
          p
            span.font-bold= transporter.full_name
            span.text-sm=< "[#{transporter.periods_for?(daily_quest.started_on).join('h -> ')}h]"

          - if transporter.vehicle.present?
            p.text-sm
              = "#{transporter.vehicle.name} / #{transporter.vehicle.number_plate}"
  .flex.items-center.justify-center.gap-3.bg-gray-100.p-2.rounded-b-lg.dark:bg-slate-700/75.dark:text-white
    - if allowed_to?(:index?, transporter, with: DailyQuests::Transporters::StepPolicy, context: { daily_quest: daily_quest })
      = link_to 'Trajets du jour', daily_quest_transporter_steps_path(daily_quest, transporter), class: 'text-sm underline'

      = link_to daily_quest_transporter_steps_path(daily_quest, transporter, format: :pdf), target: :_blank, title: 'Exporter en PDF' do
        <svg class="w-6 h-6 hover:text-green-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 20">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 18a.969.969 0 0 0 .933 1h12.134A.97.97 0 0 0 15 18M1 7V5.828a2 2 0 0 1 .586-1.414l2.828-2.828A2 2 0 0 1 5.828 1h8.239A.97.97 0 0 1 15 2v5M6 1v4a1 1 0 0 1-1 1H1m0 9v-5h1.5a1.5 1.5 0 1 1 0 3H1m12 2v-5h2m-2 3h2m-8-3v5h1.375A1.626 1.626 0 0 0 10 13.375v-1.75A1.626 1.626 0 0 0 8.375 10H7Z"/>
        </svg>

    - if allowed_to?(:send_planning?, transporter, namespace: DailyQuests, context: { daily_quest: daily_quest })
      = link_to send_planning_daily_quest_transporter_path(daily_quest, transporter), data: { turbo_method: :post, turbo_confirm: 'Voulez-vous envoyer le planning du jour à ce chauffeur par email ?' }, class: 'text-xs underline', title: 'Envoyer par email au chauffeur' do
        <svg class="w-6 h-6 hover:text-blue-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16">
          <path d="m10.036 8.278 9.258-7.79A1.979 1.979 0 0 0 18 0H2A1.987 1.987 0 0 0 .641.541l9.395 7.737Z"/>
          <path d="M11.241 9.817c-.36.275-.801.425-1.255.427-.428 0-.845-.138-1.187-.395L0 2.6V14a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V2.5l-8.759 7.317Z"/>
        </svg>

  .sortable_steps.space-y-2.mt-2 class="min-h-[300px]" data-transporter-id=transporter.id id=dom_id(transporter, 'mission')
    = render 'transporter_missions', daily_quest: daily_quest, transporter: transporter

app/views/daily_quests/show.html.slim
header.flex.flex-col.lg:flex-row.items-center.justify-between.mb-6.gap-3
  h1.text-3xl= l(@daily_quest.started_on, format: :complete_slash)

  .flex.items-center.gap-3
    - if allowed_to?(:index?, @daily_quest)
      = link_to '<< Retour au planning',
                daily_quests_path(date: @daily_quest.started_on),
                class: 'btn-back'

    - if allowed_to?(:index?, Mission, namespace: DailyQuests, context: { daily_quest: @daily_quest })
      = link_to 'Gérer les missions', daily_quest_missions_path(@daily_quest), class: 'btn-edit'

    - if allowed_to?(:destroy?, @daily_quest)
      = button_to 'Supprimer', @daily_quest,
                  class: 'btn-destroy',
                  method: :delete,
                  data: { turbo_confirm: 'Voulez-vous supprimer ce planning ?' }

div id=dom_id(@daily_quest)
  .flex.flex-col.lg:flex-row.justify-between.gap-6
    .lg:w-1/3
      - @daily_quest.missions.by_position.includes(:customer, :place).each_with_index do |mission, index|
        = link_to daily_quest_mission_steps_path(@daily_quest, mission),
                  class: "block row mission p-2 #{'active' if mission == @mission}",
                  data: { \
                    controller: 'mission', \
                    action: 'click->mission#setActive', \
                    turbo_stream: true \
                  } do
          span.block
            | Mission #{index + 1}:
            =< mission.customer.full_name
          span.block.text-sm.italic
            =< mission.place.name

    - if @mission
      .lg:w-2/3
        = turbo_frame_tag :steps, src: [@daily_quest, @mission, :steps] do
          p.dark:text-white Chargement des étapes de la missions