config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#show'

  mount GoodJob::Engine => 'good_job'

  resource :sessions, only: %i[new create destroy]
  get '/sessions' => redirect('/sessions/new')

  resources :password_resets, only: %i[new create edit update]

  resource :settings, only: %i[edit update]
  resolve('Setting') { [:settings] }

  resource :companies, only: %i[new create edit update]
  resolve('Company') { [:companies] }

  resources :users, only: %i[new create]

  namespace :me do
    resource :profile, only: %i[show edit update]
  end

  resources :customers do
    member do
      delete :archive
    end

    collection do
      get :daily
    end
  end
  resources :vehicles

  resources :places do
    collection do
      get :daily
    end
  end

  resources :transporters do
    collection do
      get :daily
    end
    scope module: :transporters do
      resources :absences, except: %i[index show]
    end
  end

  resources :daily_quests, only: %i[index show destroy] do
    member do
      post :reset
      post :duplicate_week
      post 'optimize'
    end

    scope module: :daily_quests do
      resources :missions

      resources :steps, only: %i[edit update destroy] do
        member do
          post 'optimize'
        end
      end

      resources :transporters, only: [] do
        collection do
          post :send_all_plannings
        end

        member do
          post :send_planning
        end

        scope module: :transporters do
          resources :steps, only: %i[index]
        end
      end

      resources :missions, only: [] do
        scope module: :missions do
          resources :steps, only: %i[index update]
        end
      end
    end
  end

  namespace :addresses do
    resource :search, only: :show
  end
end

app/models/daily_quest.rb
class DailyQuest < ApplicationRecord
  WAITING_TIME = 30.minutes # time before hiding steps

  enum status: { not_started: 0, pending: 1, ended: 2 }, _default: :not_started

  belongs_to :company
  has_many :missions, dependent: :destroy
  has_many :steps, through: :missions

  validates :started_on, presence: true

  accepts_nested_attributes_for :missions, reject_if: :all_blank, allow_destroy: true

  def self.clone_week!(using:)
    my_week = using.company
                   .daily_quests
                   .joins(:missions)
                   .where(started_on: (using.started_on.beginning_of_week)..(using.started_on.end_of_week))

    my_week.each do |daily|
      started_on = daily.started_on.in(1.week)
      my_daily_quest = daily.company.daily_quests.find_or_create_by(
        started_on: started_on
      )
      my_daily_quest.save!

      Rails.logger.debug my_daily_quest.inspect

      my_daily_quest.missions.delete_all
      daily.missions.each do |mission|
        my_mission = mission.dup
        my_mission.drop_duration_hours = mission.drop_duration / 60
        my_mission.drop_duration_minutes = mission.drop_duration % 60
        my_mission.daily_quest_id = my_daily_quest.id
        my_mission.save!
        Rails.logger.debug my_mission.inspect
      end
    end
  end

  def title
    I18n.l(started_on)
  end

  def recompute_missions_position
    missions.order(drop_time: :asc).each_with_index do |mission, index|
      mission.update_column :position, index + 1
    end
  end

  # def recompute_steps_position
  # missions.map(&:steps).flatten
  # end
end

# == Schema Information
#
# Table name: daily_quests
#
#  id         :bigint(8)        not null, primary key
#  started_on :date
#  status     :integer          default("not_started"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  company_id :bigint(8)
#
# Indexes
#
#  index_daily_quests_on_company_id  (company_id)
#

app/controllers/daily_quests/missions/steps_controller.rb
module DailyQuests
  module Missions
    class StepsController < ApplicationController
      before_action :set_daily_quest
      before_action :set_mission
      before_action :set_step, only: :update

      # @route GET /daily_quests/:daily_quest_id/missions/:mission_id/steps (daily_quest_mission_steps)
      def index
        authorize! Step, context: { daily_quest: @daily_quest }

        @steps = @mission.steps.all
      end

      # @route PATCH /daily_quests/:daily_quest_id/missions/:mission_id/steps/:id (daily_quest_mission_step)
      # @route PUT /daily_quests/:daily_quest_id/missions/:mission_id/steps/:id (daily_quest_mission_step)
      def update
        authorize! @step, context: { daily_quest: @daily_quest }

        return if @step.update(step_params)

        head :unprocessable_entity
      end

      private

      def set_daily_quest
        @daily_quest = company.daily_quests.find(params[:daily_quest_id])
      end

      def set_mission
        @mission = @daily_quest.missions.find(params[:mission_id])
      end

      def set_step
        @step = @daily_quest.steps.find(params[:id])
      end

      def step_params
        params.require(:step).permit(:transporter_id)
      end
    end
  end
end

app/controllers/daily_quests/missions_controller.rb
module DailyQuests
  class MissionsController < ApplicationController
    before_action :set_daily_quest
    before_action :set_mission, only: %i[show edit update destroy]

    # @route GET /daily_quests/:daily_quest_id/missions (daily_quest_missions)
    def index
      authorize! Mission, context: { daily_quest: @daily_quest }

      if params[:date].present?
        set_daily_quest_by_date
      else
        set_daily_quest
      end

      @missions = @daily_quest.missions
    end

    # @route GET /daily_quests/:daily_quest_id/missions/new (new_daily_quest_mission)
    def new
      authorize! Mission, context: { daily_quest: @daily_quest }

      @mission = @daily_quest.missions.new
    end

    # @route POST /daily_quests/:daily_quest_id/missions (daily_quest_missions)
    def create
      authorize! Mission, context: { daily_quest: @daily_quest }

      @mission = @daily_quest.missions.new(mission_params)

      respond_to do |format|
        if @mission.save
          notice = 'La mission a bien été créé.'

          format.html { redirect_to daily_quest_missions_path(@daily_quest), notice: notice }
          format.turbo_stream { flash.now[:notice] = notice }
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    # @route GET /daily_quests/:daily_quest_id/missions/:id (daily_quest_mission)
    def show
      authorize! @mission, context: { daily_quest: @mission.daily_quest }
    end

    # @route GET /daily_quests/:daily_quest_id/missions/:id/edit (edit_daily_quest_mission)
    def edit
      authorize! @mission, context: { daily_quest: @mission.daily_quest }
    end

    # @route PATCH /daily_quests/:daily_quest_id/missions/:id (daily_quest_mission)
    # @route PUT /daily_quests/:daily_quest_id/missions/:id (daily_quest_mission)
    def update
      authorize! @mission, context: { daily_quest: @mission.daily_quest }

      if @mission.update(mission_params)
        redirect_to daily_quest_mission_path(@daily_quest, @mission), notice: 'La mission a bien été mise à jour.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # @route DELETE /daily_quests/:daily_quest_id/missions/:id (daily_quest_mission)
    def destroy
      authorize! @mission, context: { daily_quest: @mission.daily_quest }

      @mission.destroy

      respond_to do |format|
        notice = 'La mission a bien été supprimée'

        format.html { redirect_to daily_quest_missions_path(date: @daily_quest.started_on), notice: notice }
        format.turbo_stream { flash.now[:notice] = notice }
      end
    end

    private

    def mission_params
      params.require(:mission).permit(
        :drop_time, :round_trip, :drop_duration_hours,
        :drop_duration_minutes, :customer_id, :place_id
      )
    end

    def set_daily_quest
      @daily_quest = company.daily_quests.find(params[:daily_quest_id])
    end

    def set_daily_quest_by_date
      @daily_quest = company.daily_quests.find_or_create_by(started_on: date)

      redirect_to daily_quest_missions_path(@daily_quest)
    end

    def set_mission
      @mission = @daily_quest.missions.find(params[:id])
    end

    def date
      if params[:date].present?
        begin
          Date.parse(params[:date])
        rescue StandardError
          Date.current
        end
      else
        Date.current
      end
    end
  end
end

app/controllers/daily_quests/steps_controller.rb
module DailyQuests
  class StepsController < ApplicationController
    before_action :set_daily_quest
    before_action :set_step

    # @route GET /daily_quests/:daily_quest_id/steps/:id/edit (edit_daily_quest_step)
    def edit
      authorize! @step, context: { daily_quest: @daily_quest }
    end

    # @route PATCH /daily_quests/:daily_quest_id/steps/:id (daily_quest_step)
    # @route PUT /daily_quests/:daily_quest_id/steps/:id (daily_quest_step)
    def update
      authorize! @step, context: { daily_quest: @daily_quest }

      if @step.update(step_params)
        render partial: 'daily_quests/step', locals: { step: @step }
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # @route DELETE /daily_quests/:daily_quest_id/steps/:id (daily_quest_step)
    def destroy
      authorize! @step, context: { daily_quest: @daily_quest }

      @step.destroy

      respond_to do |format|
        notice = 'La mission a bien été supprimée'

        format.html { redirect_to daily_quests_path(date: @daily_quest.started_on), notice: notice }
        format.turbo_stream { flash.now[:notice] = notice }
      end
    end

    # @route POST /daily_quests/:daily_quest_id/steps/:id/optimize (optimize_daily_quest_step)
    def optimize
      authorize! @step, context: { daily_quest: @daily_quest }

      Optimizer.call(@step)

      redirect_to daily_quests_path(date: @daily_quest.started_on)
    end

    private

    def step_params
      params.require(:step).permit(:description)
    end

    def set_daily_quest
      @daily_quest = company.daily_quests.find(params[:daily_quest_id])
    end

    def set_step
      @step = @daily_quest.steps.find(params[:id])
    end
  end
end

app/controllers/daily_quests/transporters/steps_controller.rb
module DailyQuests
  module Transporters
    class StepsController < ApplicationController
      before_action :set_daily_quest
      before_action :set_transporter

      # @route GET /daily_quests/:daily_quest_id/transporters/:transporter_id/steps (daily_quest_transporter_steps)
      def index
        authorize! @transporter,
                   with: DailyQuests::Transporters::StepPolicy,
                   context: { daily_quest: @daily_quest }

        @steps = @daily_quest.steps.with_all_rich_text.where(transporter: @transporter)

        respond_to do |format|
          format.html
          format.pdf do
            name = "#{@daily_quest.started_on} - #{@transporter.full_name}".parameterize(separator: '_')

            render pdf: name
          end
        end
      end

      private

      def set_daily_quest
        @daily_quest = company.daily_quests.find(params[:daily_quest_id])
      end

      def set_transporter
        @transporter = company.transporters.find(params[:transporter_id])
      end
    end
  end
end

app/controllers/daily_quests/transporters_controller.rb
module DailyQuests
  class TransportersController < ApplicationController
    before_action :set_daily_quest
    before_action :set_transporter, only: :send_planning

    # @route POST /daily_quests/:daily_quest_id/transporters/send_all_plannings (send_all_plannings_daily_quest_transporters)
    def send_all_plannings
      authorize! Transporter, context: { daily_quest: @daily_quest }

      transporters = company.daily_quests.with_attached_photo.includes(:absences)
      transporters = transporters.reject do |transporter|
        transporter.off?(@daily_quest.started_on)
      end

      transporters.each do |transporter|
        TransporterMailer
          .with(transporter: transporter, daily_quest: @daily_quest)
          .send_planning
          .deliver_later
      end

      respond_to do |format|
        notice = "Les plannings du jour sont en train d'être envoyés aux différents chauffeurs"

        format.html do
          redirect_to daily_quest_path(date: @daily_quest.started_on), notice: notice
        end
        format.turbo_stream { flash.now[:notice] = notice }
      end
    end

    # @route POST /daily_quests/:daily_quest_id/transporters/:id/send_planning (send_planning_daily_quest_transporter)
    def send_planning
      authorize! @transporter, context: { daily_quest: @daily_quest }

      TransporterMailer
        .with(transporter: @transporter, daily_quest: @daily_quest)
        .send_planning
        .deliver_later

      respond_to do |format|
        notice = "Le planning a bien été envoyé par email à #{@transporter.full_name}"

        format.html do
          redirect_to daily_quest_path(date: @daily_quest.started_on), notice: notice
        end
        format.turbo_stream { flash.now[:notice] = notice }
      end
    end

    private

    def set_daily_quest
      @daily_quest = company.daily_quests.find(params[:daily_quest_id])
    end

    def set_transporter
      @transporter = company.transporters.find(params[:id])
    end
  end
end

app/controllers/daily_quests_controller.rb
class DailyQuestsController < ApplicationController
  MAX_HOUR = 18

  before_action :set_daily_quest, only: %i[
    show destroy
    optimize duplicate_week reset
  ]

  # @route GET /daily_quests (daily_quests)
  def index
    authorize! DailyQuest

    # Planning redirect to next business day if current day is not
    unless calendar.business_day?(date)
      next_business_day = calendar.next_business_day(date)
      redirect_to daily_quests_path(date: next_business_day)
      return
    end

    # Planning redirect to tomorrow if todays missions are ended
    if params[:date].blank? && Time.current.hour >= MAX_HOUR
      next_business_day = calendar.next_business_day(Date.current)
      redirect_to daily_quests_path(date: next_business_day)
      return
    end

    @daily_quest = company.daily_quests.find_or_create_by(started_on: date)

    transporters = authorized_scope(company.transporters.includes(:absences))
    @transporters = transporters.sort_by_courses_for(@daily_quest)
  end

  # @route GET /daily_quests/:id (daily_quest)
  def show
    authorize! @daily_quest

    @mission = if params[:currentMissionId].present?
      @daily_quest.missions.find(params[:currentMissionId])
    else
      @daily_quest.missions.first
    end
  end

  # @route DELETE /daily_quests/:id (daily_quest)
  def destroy
    authorize! @daily_quest

    @daily_quest.missions.destroy_all

    redirect_to daily_quests_path, notice: 'Toutes les missions du jour ont bien été supprimées'
  end

  # @route POST /daily_quests/:id/optimize (optimize_daily_quest)
  def optimize
    authorize! @daily_quest

    steps = @daily_quest.missions.map(&:steps).flatten.select(&:single?).compact

    OptimizerJob.perform_later(steps.map(&:id))

    head :ok
  end

  # @route POST /daily_quests/:id/duplicate_week (duplicate_week_daily_quest)
  def duplicate_week
    authorize! @daily_quest

    DuplicateWeekJob.perform_later(@daily_quest)

    redirect_to daily_quests_path(date: @daily_quest.started_on), notice: 'La semaine est en cours de duplication. Veuillez patienter, cela peut prendre quelques minutes. La page sera rafraîchie une fois la copie terminée'
  end

  # @route POST /daily_quests/:id/reset (reset_daily_quest)
  def reset
    authorize! @daily_quest

    ResetDailyQuest.call(@daily_quest)

    redirect_to daily_quests_path(date: @daily_quest.started_on), notice: 'Le planning du jour a bien été réinitialisé'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_daily_quest
    @daily_quest = company.daily_quests.find(params[:id])
  end

  def date
    if params[:date].present?
      begin
        Date.parse(params[:date])
      rescue StandardError
        Date.current
      end
    else
      Date.current
    end
  end
end

app/helpers/missions_helper.rb
module MissionsHelper
  def value_for_drop_duration_hours(mission)
    return mission.drop_duration_hours if mission.new_record?

    mission.drop_duration / 60
  end

  def value_for_drop_duration_minutes(mission)
    return mission.drop_duration_minutes if mission.new_record?

    mission.drop_duration % 60
  end
end

app/views/daily_quests/missions/_empty_missions.html.slim
.panel-warning.p-4
  - if allowed_to?(:create?, Mission, namespace: DailyQuests, context: { daily_quest: daily_quest })
    p
      | Il n'y a pas encore de missions,
      =< link_to 'ajouter la première',
                 new_daily_quest_mission_path(daily_quest),
                 class: 'underline',
                 data: { turbo_frame: dom_id(Mission.new) }

  - else
    p.mb-2 Avant de pouvoir ajouter une mission, vous devez vous assurer que les éléments suivants sont correctement configurés:

    - if company.customers.enabled.empty?
      p.mt-1
        | Il n'y a pas encore de clients,
        =< link_to 'ajouter le premier', new_customer_path, class: 'underline'

    - if company.places.enabled.empty?
      p.mt-1
        | Il n'y a pas encore de lieux,
        =< link_to 'ajouter le premier', new_place_path, class: 'underline'

    - if company.transporters.empty?
      p.mt-1
        | Il n'y a pas encore de chauffeurs,
        =< link_to 'ajouter le premier', new_transporter_path, class: 'underline'

    - if company.vehicles.enabled.normal.empty?
      p.mt-1
        | Il n'y a pas encore de véhicules,
        =< link_to 'ajouter le premier', new_vehicle_path, class: 'underline'

app/views/daily_quests/missions/_form.html.slim
= simple_form_for [mission.daily_quest, mission],
                  html: { \
                    class: 'row p-3 hover:bg-gray-50 dark:hover:bg-gray-700/75 transition-colors', \
                    data: { controller: 'missions' } \
                  } do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .space-y-5
    = f.association :customer,
                    collection: customers_select_options,
                    include_blank: false,
                    input_html: { \
                      class: 'w-full', \
                      data: { \
                        controller: 'slim-select' \
                      } \
                    },
                    wrapper_html: { class: 'w-full' }

    = f.association :place,
                    collection: places_select_options,
                    include_blank: false,
                    input_html: { \
                      class: 'w-full', \
                      data: { \
                        controller: 'slim-select' \
                      } \
                    },
                    wrapper_html: { class: 'w-full' }

    = f.input :drop_time, as: :time, html5: true,
              input_html: { \
                value: (f.object.drop_time.strftime('%H:%M') if f.object.persisted?) \
              }, \
              wrapper_html: { class: 'w-full' }

    div data-controller="round-trip"
      = f.input :round_trip,
                as: :boolean,
                input_html: { \
                  data: { \
                    round_trip_target: 'booleanInput', \
                    action: 'change->round-trip#toggleDuration' \
                  } \
                }


      div data-round-trip-target="durationInput"
        = f.input :drop_duration_hours,
                  as: :integer,
                  wrapper_html: { class: 'w-full mt-5' },
                  input_html: { \
                    value: value_for_drop_duration_hours(f.object) \
                  }
        = f.input :drop_duration_minutes,
                  as: :integer,
                  include_blank: false,
                  wrapper_html: { class: 'w-full mt-5' },
                  input_html: { \
                    value: value_for_drop_duration_minutes(f.object) \
                  }

    = f.button :submit, 'Enregistrer', class: 'btn-add w-full'

    - if mission.persisted?
      = link_to 'Retour',
                daily_quest_mission_path(mission.daily_quest, mission),
                class: 'block underline text-sm text-center'
    - else
      = link_to 'Retour',
                daily_quest_missions_path(mission.daily_quest),
                class: 'block underline text-sm text-center',
                data: { \
                  controller: 'missions', \
                  action: 'click->missions#close' \
                }

app/views/daily_quests/missions/_map.html.slim
#map.w-full class="h-[500px]" data-controller="mission-map" data-mission-map-target="map" data-mission-map-steps-value=mission.steps.map(&:route).to_json data-mission-map-gesture-handling-value=options.map_gesture_handling.to_s

app/views/daily_quests/missions/_mission.html.slim
= turbo_frame_tag mission do
  - daily_quest = mission.daily_quest
  - customer = mission.customer
  - place = mission.place
  - steps = mission.steps

  .flex.flex-col.justify-between.row.p-3.hover:bg-gray-50.dark:hover:bg-gray-700/75.transition-colors.gap-3 class="!mb-0"
    .space-y-5
      .flex.items-center.gap-3
        - if customer.photo.attached?
          = image_tag url_for(customer.photo), class: 'w-16 rounded-full object-cover'
        .space-y-1
          p= customer.full_name
          p.text-gray-500.text-xs= customer.address.label

      .flex.items-center.gap-3
        - if place.photo.attached?
          = image_tag url_for(place.photo), class: 'w-16 rounded-full object-cover'
        .space-y-1
          p= place.name
          p.text-gray-500.text-xs= place.address.label

      - steps.each.with_index do |step, index|
        p.border-b.dark:border-gray-600.dark:text-gray-300
          - if steps.count == 1
            | Trajet unique
          - elsif index == 0
            | Départ
          - else
            | Retour

        = render 'daily_quests/steps/metadata', step: step

    footer.flex.items-center.justify-between.gap-1.mt-3
      - if allowed_to?(:show?, mission, context: { daily_quest: daily_quest })
        = link_to 'Détails',
                  daily_quest_mission_steps_path(daily_quest, mission),
                  data: { turbo_frame: :steps },
                  class: 'btn-show w-full'

      - if allowed_to?(:update?, mission, context: { daily_quest: daily_quest })
        = link_to 'Modifier',
                  edit_daily_quest_mission_path(daily_quest, mission),
                  class: 'btn-edit w-full'

      - if allowed_to?(:destroy?, mission, context: { daily_quest: daily_quest })
        = link_to 'Supprimer',
                  daily_quest_mission_path(daily_quest, mission),
                  class: 'btn-destroy w-full',
                  data: { turbo_method: :delete, turbo_confirm: 'Voulez-vous supprimer cette mission ?' }

app/views/daily_quests/missions/_step.html.slim
.row.p-2.cursor-pointer.space-y-2 class="!mb-0" data-index=step_counter data-action="mouseover->steps#highlight mouseout->steps#unhighlight"
  = render 'daily_quests/steps/label', step: step

  p.text-sm= step.title

  = render 'daily_quests/steps/metadata', step: step

  .text-sm.text-gray-400== step.description

app/views/daily_quests/missions/_steps.html.slim
.mb-3.space-y-3 data-controller="steps"
  = render partial: 'daily_quests/missions/step', collection: steps

  = link_to 'Fermer',
            daily_quest_missions_path(steps.first.mission.daily_quest),
            class: 'block underline text-sm text-center dark:text-white',
            data: { \
              controller: 'steps', \
              action: 'click->steps#close' \
            }

app/views/daily_quests/missions/create.turbo_stream.slim
= turbo_stream.prepend :missions do
  = render 'mission', mission: @mission

= turbo_stream.update dom_id(Mission.new), ''
= turbo_stream.update :empty_missions, ''

app/views/daily_quests/missions/destroy.turbo_stream.slim
= render_turbo_stream_flash_messages
= turbo_stream.remove dom_id(@mission)

- if @mission.steps.empty?
  = turbo_stream.update :empty_missions do
    = render 'empty_missions', daily_quest: @daily_quest

app/views/daily_quests/missions/edit.html.slim
h1 Modifier mission

= turbo_frame_tag dom_id(@mission) do
  = render 'form', mission: @mission

app/views/daily_quests/missions/index.html.slim
- unless current_user.standard?
  details.panel-info.mb-5 open=options.show_help?
    summary.cursor-pointer Explications à lire

    .mt-3
      p.mb-3 Cette page permet de configurer les missions de transport pour la journée du <strong>#{l(@daily_quest.started_on)}</strong>:

      .mb-3
        p.mb-1 Pour chaque mission, spécifiez:
        ul.list-disc.list-inside.mb-2
          li le <strong>client</strong> à transporter
          li le <strong>lieu</strong> où il doit être déposé
          li l'<strong>heure</strong> à laquelle il doit être déposé
          li la <strong>durée</strong> de la consultation en minutes

        p Note: L'heure à laquelle chercher le client chez lui et l'heure de retour seront automatiquement calculées par l'algorithme.

    p Pour ajouter une nouvelle mission, cliquer sur le bouton <span class="btn-add !text-xs">Ajouter une mission +</span> puis enregistrez.
    p Pour modifier une mission, cliquez sur le lien <span class="btn-edit !text-xs">Modifier</span> en bas de la carte de la mission.
    p Pour supprimer une mission, cliquez sur le lien <span class="btn-destroy !text-xs">Supprimer</span> en bas de la carte de la mission.

- allowed_to_create_mission = allowed_to?(:create?, Mission, context: { daily_quest: @daily_quest })

header.flex.flex-col.lg:flex-row.items-center.justify-between.mb-6.gap-3
  h1.text-3xl Missions du #{l(@daily_quest.started_on, format: :complete_slash)}

  = render 'daily_quests/navigate_planning_days' do
    - if allowed_to?(:index?, @daily_quest)
      = link_to '<< Retour au planning',
                daily_quests_path(date: @daily_quest.started_on),
                class: 'btn-back'

    - if allowed_to_create_mission
      = link_to 'Ajouter une mission +',
                new_daily_quest_mission_path(@daily_quest),
                class: 'btn-add',
                data: { turbo_frame: dom_id(Mission.new) }

- if allowed_to_create_mission
  = turbo_frame_tag dom_id(Mission.new)
= turbo_frame_tag :steps

- if @missions.empty?
  #empty_missions
    = render 'empty_missions', daily_quest: @daily_quest

#missions.grid.grid-cols-1.md:grid-cols-2.lg:grid-cols-3.xl:grid-cols-4.gap-4
  = render @missions

app/views/daily_quests/missions/new.html.slim
h1 Nouvelle mission

= turbo_frame_tag dom_id(@mission) do
  .lg:w-1/2.mx-auto
    = render 'form', mission: @mission

app/views/daily_quests/missions/show.html.slim
= render 'mission', mission: @mission