config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#show'

  mount GoodJob::Engine => 'good_job'

  resource :sessions, only: %i[new create destroy]
  get '/sessions' => redirect('/sessions/new')

  resources :password_resets, only: %i[new create edit update]

  resource :settings, only: %i[edit update]
  resolve('Setting') { [:settings] }

  resource :companies, only: %i[new create edit update]
  resolve('Company') { [:companies] }

  resources :users, only: %i[new create]

  namespace :me do
    resource :profile, only: %i[show edit update]
  end

  resources :customers do
    member do
      delete :archive
    end

    collection do
      get :daily
    end
  end
  resources :vehicles

  resources :places do
    collection do
      get :daily
    end
  end

  resources :transporters do
    collection do
      get :daily
    end
    scope module: :transporters do
      resources :absences, except: %i[index show]
    end
  end

  resources :daily_quests, only: %i[index show destroy] do
    member do
      post :reset
      post :duplicate_week
      post 'optimize'
    end

    scope module: :daily_quests do
      resources :missions

      resources :steps, only: %i[edit update destroy] do
        member do
          post 'optimize'
        end
      end

      resources :transporters, only: [] do
        collection do
          post :send_all_plannings
        end

        member do
          post :send_planning
        end

        scope module: :transporters do
          resources :steps, only: %i[index]
        end
      end

      resources :missions, only: [] do
        scope module: :missions do
          resources :steps, only: %i[index update]
        end
      end
    end
  end

  namespace :addresses do
    resource :search, only: :show
  end
end

app/models/transporter.rb
class Transporter < User
  include Archivable
  include Optionable

  attr_accessor :longitude, :latitude, :driving, :address_label

  attribute :availabilities, AvailabilitiesOption.to_type

  belongs_to :vehicle, optional: true
  has_one :address, as: :addressable, dependent: :destroy
  has_many :absences, dependent: :destroy
  has_many :steps, dependent: :nullify

  accepts_nested_attributes_for :address, reject_if: :all_blank

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
  validates :phone, presence: true, if: :mandatory_phone?
  validates :phone,
            numericality: true,
            length: { is: 10 },
            allow_blank: -> { !mandatory_phone? }
  validates :vehicle, allow_blank: true, uniqueness: true

  def self.sort_by_courses_for(daily_quest)
    all.sort_by { |t| (t.step_ids & daily_quest.step_ids).count }
  end

  def periods_for?(my_date)
    day = my_date.to_date.strftime('%A').downcase
    period_name = availabilities[day].to_sym
    AvailabilitiesOption::PERIODS[period_name]
  end

  def available_at?(started_at, arrival_at)
    periods = periods_for?(started_at)
    Rails.logger.info [[started_at.hour, periods.first], [arrival_at.hour, periods.second]]
    started_at.hour >= periods.first && arrival_at.hour <= periods.second
  end

  def off?(date = Time.current)
    absences.present_today?(date)
  end

  def no_vehicle?
    vehicle.nil?
  end

  def current_absence(date = Date.current)
    absences
      .not_attending
      .where('started_on <= :date AND ended_on >= :date', date: date)
      .last
  end

  def driving?
    !!driving
  end

  private

  def mandatory_phone?
    options.validate_phone_for_transporters?
  end
end

# == Schema Information
#
# Table name: users
#
#  id                                  :bigint(8)        not null, primary key
#  email                               :string           not null
#  crypted_password                    :string
#  salt                                :string
#  created_at                          :datetime         not null
#  updated_at                          :datetime         not null
#  remember_me_token                   :string
#  remember_me_token_expires_at        :datetime
#  reset_password_token                :string
#  reset_password_token_expires_at     :datetime
#  reset_password_email_sent_at        :datetime
#  access_count_to_reset_password_page :integer          default(0)
#  type                                :string
#  first_name                          :string
#  last_name                           :string
#  phone                               :string
#  role                                :integer          default("standard"), not null
#  availabilities                      :json             not null
#  archived_at                         :datetime
#  vehicle_id                          :bigint(8)
#  company_id                          :bigint(8)
#
# Indexes
#
#  index_users_on_company_id            (company_id)
#  index_users_on_email_and_company_id  (email,company_id) UNIQUE
#  index_users_on_remember_me_token     (remember_me_token)
#  index_users_on_reset_password_token  (reset_password_token)
#  index_users_on_vehicle_id            (vehicle_id)
#

app/controllers/daily_quests/transporters/steps_controller.rb
module DailyQuests
  module Transporters
    class StepsController < ApplicationController
      before_action :set_daily_quest
      before_action :set_transporter

      # @route GET /daily_quests/:daily_quest_id/transporters/:transporter_id/steps (daily_quest_transporter_steps)
      def index
        authorize! @transporter,
                   with: DailyQuests::Transporters::StepPolicy,
                   context: { daily_quest: @daily_quest }

        @steps = @daily_quest.steps.with_all_rich_text.where(transporter: @transporter)

        respond_to do |format|
          format.html
          format.pdf do
            name = "#{@daily_quest.started_on} - #{@transporter.full_name}".parameterize(separator: '_')

            render pdf: name
          end
        end
      end

      private

      def set_daily_quest
        @daily_quest = company.daily_quests.find(params[:daily_quest_id])
      end

      def set_transporter
        @transporter = company.transporters.find(params[:transporter_id])
      end
    end
  end
end

app/controllers/daily_quests/transporters_controller.rb
module DailyQuests
  class TransportersController < ApplicationController
    before_action :set_daily_quest
    before_action :set_transporter, only: :send_planning

    # @route POST /daily_quests/:daily_quest_id/transporters/send_all_plannings (send_all_plannings_daily_quest_transporters)
    def send_all_plannings
      authorize! Transporter, context: { daily_quest: @daily_quest }

      transporters = company.daily_quests.with_attached_photo.includes(:absences)
      transporters = transporters.reject do |transporter|
        transporter.off?(@daily_quest.started_on)
      end

      transporters.each do |transporter|
        TransporterMailer
          .with(transporter: transporter, daily_quest: @daily_quest)
          .send_planning
          .deliver_later
      end

      respond_to do |format|
        notice = "Les plannings du jour sont en train d'être envoyés aux différents chauffeurs"

        format.html do
          redirect_to daily_quest_path(date: @daily_quest.started_on), notice: notice
        end
        format.turbo_stream { flash.now[:notice] = notice }
      end
    end

    # @route POST /daily_quests/:daily_quest_id/transporters/:id/send_planning (send_planning_daily_quest_transporter)
    def send_planning
      authorize! @transporter, context: { daily_quest: @daily_quest }

      TransporterMailer
        .with(transporter: @transporter, daily_quest: @daily_quest)
        .send_planning
        .deliver_later

      respond_to do |format|
        notice = "Le planning a bien été envoyé par email à #{@transporter.full_name}"

        format.html do
          redirect_to daily_quest_path(date: @daily_quest.started_on), notice: notice
        end
        format.turbo_stream { flash.now[:notice] = notice }
      end
    end

    private

    def set_daily_quest
      @daily_quest = company.daily_quests.find(params[:daily_quest_id])
    end

    def set_transporter
      @transporter = company.transporters.find(params[:id])
    end
  end
end

app/controllers/transporters/absences_controller.rb
module Transporters
  class AbsencesController < ApplicationController
    before_action :set_transporter
    before_action :set_absence, only: %i[edit update destroy]

    # @route GET /transporters/:transporter_id/absences/new (new_transporter_absence)
    def new
      authorize! Absence, context: { transporter: @transporter }

      @absence = @transporter.absences.new
    end

    # @route POST /transporters/:transporter_id/absences (transporter_absences)
    def create
      authorize! Absence, context: { transporter: @transporter }

      @absence = @transporter.absences.new(absence_params)

      respond_to do |format|
        if @absence.save
          format.html { redirect_to transporter_path(@transporter), notice: "L'absence a bien été créé" }
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    # @route GET /transporters/:transporter_id/absences/:id/edit (edit_transporter_absence)
    def edit
      authorize! @absence, context: { transporter: @transporter }
    end

    # @route PATCH /transporters/:transporter_id/absences/:id (transporter_absence)
    # @route PUT /transporters/:transporter_id/absences/:id (transporter_absence)
    def update
      authorize! @absence, context: { transporter: @transporter }

      respond_to do |format|
        if @absence.update(absence_params)
          format.html { redirect_to transporter_path(@transporter), notice: "L'absence a bien été modifiée" }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    # @route DELETE /transporters/:transporter_id/absences/:id (transporter_absence)
    def destroy
      authorize! @absence, context: { transporter: @transporter }

      @absence.destroy

      respond_to do |format|
        format.html { redirect_to transporter_path(@transporter), notice: "L'absence a bien été supprimée" }
      end
    end

    private

    def set_transporter
      @transporter = company.transporters.find(params[:transporter_id])
    end

    def set_absence
      @absence = @transporter.absences.find(params[:id])
    end

    def absence_params
      params.require(:absence).permit(
        :started_on, :ended_on, :reason, :transporter_id
      )
    end
  end
end

app/controllers/transporters_controller.rb
class TransportersController < ApplicationController
  before_action :set_transporter, only: %i[show edit update destroy]

  # @route GET /transporters (transporters)
  def index
    authorize! Transporter

    transporters = authorized_scope(company.transporters)

    respond_to do |format|
      format.html { @pagy, @transporters = pagy(transporters) }
      format.json { @transporters = transporters }
    end
  end

  # @route GET /transporters/new (new_transporter)
  def new
    authorize! Transporter

    @transporter = company.transporters.new
    @transporter.build_address
  end

  # @route POST /transporters (transporters)
  def create
    authorize! Transporter

    @transporter = company.transporters.new(transporter_params)

    respond_to do |format|
      if @transporter.save
        format.html do
          redirect_url = params[:mode] == 'save_and_create_new' ? new_transporter_path : transporter_path(@transporter)
          redirect_to redirect_url, notice: 'Le chauffeur a bien été créé.'
        end
        format.json { render :show, status: :created, location: @transporter }
      else
        @transporter.build_address(label: transporter_params.dig(:address_attributes, :label))

        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transporter.errors, status: :unprocessable_entity }
      end
    end
  end

  # @route GET /transporters/:id (transporter)
  def show
    authorize! @transporter

    @pagy, @absences = pagy(@transporter.absences.order(started_on: :desc))
  end

  # @route GET /transporters/:id/edit (edit_transporter)
  def edit
    authorize! @transporter

    @transporter.build_address if @transporter.address.blank?
  end

  # @route PATCH /transporters/:id (transporter)
  # @route PUT /transporters/:id (transporter)
  def update
    authorize! @transporter

    respond_to do |format|
      if @transporter.update(transporter_params)
        format.html { redirect_to transporter_url(@transporter), notice: 'Le chauffeur a bien été mis à jour.' }
      else
        @transporter.build_address(label: transporter_params.dig(:address_attributes, :label))

        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # @route DELETE /transporters/:id (transporter)
  def destroy
    authorize! @transporter

    @transporter.destroy

    respond_to do |format|
      format.html { redirect_to transporters_url, notice: 'Le chauffeur a bien été supprimé.' }
      format.json { head :no_content }
    end
  end

  # @route GET /transporters/daily (daily_transporters)
  def daily
    authorize! Transporter

    date = params[:date].presence || Date.current

    @daily_quest = company.daily_quests.find_or_create_by(started_on: date)

    transporters_by_ids = {}

    steps_done = @daily_quest.steps.where('(arrival_at  < ?)  ', Time.current)

    steps_done.each do |step|
      next unless (transporter = step.transporter)

      transporters_by_ids[transporter.id] = step # uniquifier
    end

    steps_doing = @daily_quest.steps.where('(started_at  < ? and arrival_at  > ?)  ', Time.current, Time.current)

    # get remaining steps by reverse, that way we keep to get the first as last
    steps_doing.each do |step|
      next unless (transporter = step.transporter)

      transporters_by_ids[transporter.id] = step # uniquifier
    end

    @transporters = []
    transporters_by_ids.each do |_id, step|
      transporter = step.transporter
      locations = step.route['positions']

      step_duration = step.arrival_at - step.started_at
      remaining_duration = step.arrival_at - Time.current
      done_duration = step_duration - remaining_duration + 0.01

      Rails.logger.info remaining_duration
      if remaining_duration.negative?
        transporter.driving = false
        longitude, latitude = locations.last
        Rails.logger.info "#{step.title}  ******* #{transporter.first_name} #{transporter.last_name} stopped @ [#{longitude} ,  #{latitude}] for #{step.arrival_at} ******* "
      else
        transporter.driving = true
        nb_locations = locations.count
        no_point = (done_duration / step_duration.to_f * nb_locations).floor

        longitude, latitude = locations[no_point]
        Rails.logger.info " #{step.title} #{remaining_duration} | #{done_duration} / #{step_duration.to_f} * #{nb_locations} ******* #{transporter.inspect} running @ #{no_point}:  [#{longitude} ,  #{latitude}] ******* "
      end

      transporter.latitude = latitude
      transporter.longitude = longitude
      @transporters << transporter
    end

    # Add missing transporters to be shown on map
    # at their home address.
    transporter_ids = @transporters.map(&:id)
    @transporters << company.transporters.where.not(id: transporter_ids)
    @transporters = @transporters.flatten

    respond_to do |format|
      format.json { render :index }
    end
  end

  private

  def set_transporter
    @transporter = company.transporters.find(params[:id])
  end

  def transporter_params
    permitted_attributes = [
      :first_name, :last_name, :email, :phone,
      :password, :password_confirmation,
      :started_time, :ended_time, :details,
      :vehicle_id, { availabilities: %i[
                       monday tuesday wednesday thursday
                       friday saturday sunday
                     ],
                     address_attributes: %i[id label] }
    ]

    permitted_attributes.push(:photo) if options.enable_transporter_photo?

    params.require(:transporter).permit(permitted_attributes)
  end
end

app/views/transporters/_form.html.slim
= simple_form_for(@transporter) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  - if f.object.errors.any?
    ul.list-disc.list-inside.panel-error.mb-6
      - f.object.errors.full_messages.each do |message|
        li= message

  .flex.flex-col.lg:flex-row.justify-between.gap-3.mb-6
    = f.input :first_name, as: :string,
              wrapper_html: { class: 'w-full' }
    = f.input :last_name, as: :string,
              wrapper_html: { class: 'w-full' }

    - if options.enable_transporter_photo?
      div
        = f.input :photo, as: :file

        - if f.object.photo.attached?
          p.mt-3.text-center= image_tag url_for(f.object.photo), class: 'max-w-[100px] rounded-full object-cover'

  .flex.flex-col.lg:flex-row.justify-between.gap-3.mb-6
    = f.input :phone, as: :string,
              wrapper_html: { class: 'w-full' },
              required: options.validate_phone_for_transporters?

    = f.input :email, as: :email,
              wrapper_html: { class: 'w-full' }

  .flex.flex-col.lg:flex-row.justify-between.gap-3.mb-6
    = f.input :password, as: :password,
              wrapper_html: { class: 'w-full' },
              required: f.object.new_record?
    = f.input :password_confirmation, as: :password,
              wrapper_html: { class: 'w-full' },
              required: f.object.new_record?

  .flex.flex-col.lg:flex-row.justify-between.gap-3.mb-6
    = f.simple_fields_for :address do |ff|
      = ff.input :label,
                 input_html: { \
                   data: { \
                     controller: 'address', \
                     address_search_url_value: addresses_search_path \
                   } \
                 },
                 collection: [ff.object.label].compact,
                 prompt: 'Chercher une adresse',
                 include_blank: false,
                 wrapper_html: { class: 'w-full' }

    - vehicles = company.vehicles.enabled.normal.with_attached_photo.where.missing(:transporter).distinct
    - if f.object.vehicle.present?
      - ids = vehicles.ids << f.object.vehicle.id
      - vehicles = company.vehicles.find(ids)

    = f.association :vehicle,
                    collection: vehicles_select_options(vehicles),
                    include_blank: 'Sélectionner un véhicule',
                    wrapper_html: { class: 'w-full' },
                    input_html: { \
                      data: { \
                        controller: 'slim-select' \
                      } \
                    }

  = f.simple_fields_for :availabilities, f.object.availabilities do |ff|
    .flex.flex-col.lg:flex-row.items-center.gap-3.mb-3
      = ff.input :monday, collection: AvailabilitiesOption::AVAILABILITIES, include_blank: false, wrapper_html: { class: 'w-full' }
      = ff.input :tuesday, collection: AvailabilitiesOption::AVAILABILITIES, include_blank: false, wrapper_html: { class: 'w-full' }
      = ff.input :wednesday, collection: AvailabilitiesOption::AVAILABILITIES, include_blank: false, wrapper_html: { class: 'w-full' }
      = ff.input :thursday, collection: AvailabilitiesOption::AVAILABILITIES, include_blank: false, wrapper_html: { class: 'w-full' }

    .flex.flex-col.lg:flex-row.items-center.gap-3.mb-3
      = ff.input :friday, collection: AvailabilitiesOption::AVAILABILITIES, include_blank: false, wrapper_html: { class: 'w-full' }
      = ff.input :saturday, collection: AvailabilitiesOption::AVAILABILITIES, include_blank: false, wrapper_html: { class: 'w-full' }
      = ff.input :sunday, collection: AvailabilitiesOption::AVAILABILITIES, include_blank: false, wrapper_html: { class: 'w-full' }

  .flex.flex-col.lg:flex-row.justify-between.gap-6.mb-6.mt-6
    = f.input :details, as: :rich_text_area,
              wrapper_html: { class: 'w-full' }

  .flex.items-center.gap-3
    = f.button :submit

    - if @transporter.new_record?
      = f.button :button, 'Valider et créer nouveau chauffeur >>', type: :submit, name: :mode, value: 'save_and_create_new'

app/views/transporters/_map_popup.html.slim
.text-center
  = link_to transporter_path(transporter), class: 'block mb-1' do
    = image_tag polymorphic_path(transporter.photo), class: 'w-16 h-16 object-cover mx-auto'

  p.font-bold= transporter.full_name

  p.text-gray-500.dark:text-white.italic
    span.underline Adresse domicile:
    br
    = transporter.address.label

  = phone_to transporter.phone, formatted_phone_number(transporter.phone), class: 'block text-blue-500 dark:text-blue-200 mb-2'

  - if transporter.driving?
    p.panel-success.animate-pulse class="!text-xs !p-1" En déplacement
  - else
    p.panel-warning.text-xs class="!text-xs !p-1" A l'arrêt

app/views/transporters/_transporter.html.slim
details.row id=dom_id(transporter)
  summary.flex.flex-col.lg:flex-row.items-center.gap-3.justify-between.p-2.relative
    .absolute.-top-2.-left-2
    .flex.items-center.gap-2
      - if transporter.photo.attached?
        = image_tag url_for(transporter.photo), class: 'w-16 h-16 rounded-full object-cover'
      div
        p
          span.font-bold= transporter.full_name

          - if transporter.off?
            span.rounded.px-1.py-1.bg-yellow-500.text-white.rounded-lg.text-sm.ml-2.mb-1.inline-block.animate-pulse
              = 'Absent'

        - if transporter.address.present?
          p.italic.text-gray-500= transporter.address.label
        .text-sm
          - if transporter.vehicle.nil?
            .flex.items-center.gap-3
              span.text-orange-500 ⚠️ Chauffeur sans véhicule

              - if allowed_to?(:update?, transporter)
                = simple_form_for(transporter) do |f|
                  = f.association :vehicle,
                                  collection: vehicles_select_options(company.vehicles.enabled.normal.with_attached_photo.where.missing(:transporter)),
                                  label: false,
                                  hint: false,
                                  include_blank: 'Sélectionner un véhicule',
                                  wrapper_html: { class: 'w-full' },
                                  input_html: { \
                                    data: { \
                                      controller: 'slim-select', \
                                      action: 'change->slim-select#submit' \
                                    } \
                                  }

          - elsif allowed_to?(:show?, transporter.vehicle)
            = link_to vehicle_path(transporter.vehicle), class: 'flex items-center gap-1' do
              - if transporter.vehicle.photo.attached?
                = image_tag transporter.vehicle.photo, class: 'w-6 h-6 object-cover rounded-full'
              = "#{transporter.vehicle.name} / #{transporter.vehicle.number_plate}"

    .flex.items-center.gap-3
      - if allowed_to?(:show?, transporter)
        = link_to 'Profil chauffeur', transporter_path(transporter), class: 'btn-show'

      - if allowed_to?(:update?, transporter)
        = link_to 'Modifier', edit_transporter_path(transporter), class: 'btn-edit'

      - if allowed_to?(:destroy?, transporter)
        = button_to 'Supprimer', transporter,
                    class: 'btn-destroy',
                    method: :delete,
                    data: { turbo_confirm: 'Voulez-vous supprimer ce chauffeur ?' }

  .p-2.border-t.dark:border-gray-600
    p
      strong Téléphone:
      =< formatted_phone_number(transporter.phone)
    p
      strong Email:
      =< transporter.email

    = transporter.details

app/views/transporters/edit.html.slim
header.flex.flex-col.lg:flex-row.items-center.justify-between.mb-6.gap-3
  h1.text-3xl Modifier un chauffeur

  - if allowed_to?(:show?, @transporter)
    = link_to '<< Retour au chauffeur', transporter_path(@transporter), class: 'btn-back'

= render 'form', transporter: @transporter

app/views/transporters/index.html.slim
header.flex.flex-col.lg:flex-row.items-center.justify-between.mb-6.gap-3
  h1.text-3xl Chauffeurs

  - if allowed_to?(:create?, Transporter)
    = link_to 'Ajouter un chauffeur', new_transporter_path, class: 'btn-add'

- unless current_user.standard?
  details.panel-info.mb-5 open=options.show_help?
    summary.cursor-pointer Explications à lire
    .mt-3
      p.mb-3 Les chauffeurs à qui assigner les missions de transport sont à spécifier sur cette page.
      p Vous pouvez configurer les absences des chauffeurs pour une période donnée en cliquant sur "Profil chauffeur". Les absences sont prises en considération dans l'attribution automatique des missions de transport aux chauffeurs.

- if @transporters.any?
  == pagy_nav(@pagy) if @pagy.pages > 1

  #transporters
    = render @transporters

  == pagy_nav(@pagy) if @pagy.pages > 1

  - if options.enable_transporters_map?
    div data-controller="global-map" data-global-map-transporters-url-value=transporters_path
      #map class="h-[500px]" data-global-map-target="map"

- else
  p.panel-warning.p-4
    | Il n'y a pas encore de chauffeurs -

    - if allowed_to?(:create?, Transporter)
      =< link_to 'Ajouter le premier', new_transporter_path, class: 'underline'

app/views/transporters/new.html.slim
header.flex.flex-col.lg:flex-row.items-center.justify-between.mb-6.gap-3
  h1.text-3xl Ajouter un chauffeur

  - if allowed_to?(:index?, Transporter)
    = link_to '<< Retour aux chauffeurs', transporters_path, class: 'btn-back'

= render 'form', transporter: @transporter

app/views/transporters/show.html.slim
header.flex.flex-col.lg:flex-row.items-center.justify-between.mb-6.gap-3
  h1.text-3xl= @transporter.full_name

  .flex.items-center.gap-2
    - if allowed_to?(:index?, Transporter)
      = link_to '<< Retour aux chauffeurs', transporters_path, class: 'btn-back'

    - if allowed_to?(:update?, @transporter)
      = link_to 'Modifier', edit_transporter_path(@transporter), class: 'btn-edit'

    - if allowed_to?(:destroy?, @transporter)
      = button_to 'Supprimer', @transporter,
                  class: 'btn-destroy',
                  method: :delete,
                  data: { turbo_confirm: 'Voulez-vous supprimer ce chauffeur ?' }

.row.p-4.mb-3 id=dom_id(@transporter)
  - if @transporter.photo.attached?
    p.mb-3= image_tag url_for(@transporter.photo), class: 'w-32'

  p
    strong Téléphone:
    =< formatted_phone_number(@transporter.phone)
  p
    strong Email:
    =< @transporter.email

  div
    p: strong Détails:
    = @transporter.details

  - if @transporter.address.present?
    p
      strong Adresse:
      =< @transporter.address.label

  - if @transporter.vehicle.present?
    p
      strong Véhicule:
      =< @transporter.vehicle.name

- if @transporter.vehicle.blank?
  .panel-warning.mb-6
    p.font-bold.mb-1 ⚠️ Chauffeur sans véhicule
    p.mb-2 Aucun véhicule n'est configuré pour ce chauffeur. Vous ne pourrez pas lui assigner de missions sans véhicule.

    = simple_form_for(@transporter) do |f|
      = f.association :vehicle,
                      collection: vehicles_select_options(company.vehicles.enabled.normal.with_attached_photo.where.missing(:transporter).distinct),
                      label: false,
                      hint: false,
                      include_blank: 'Sélectionner un véhicule',
                      wrapper_html: { class: 'w-full' },
                      input_html: { \
                        data: { \
                          controller: 'slim-select', \
                          action: 'change->slim-select#submit' \
                        } \
                      }

section.mb-6.dark:text-white
  header.flex.flex-col.lg:flex-row.items-center.justify-between.mb-6.gap-3
    h2.text-xl Les présences / absences

    - if allowed_to?(:create?, Absence, namespace: Transporters, context: { transporter: @transporter })
      = link_to 'Ajouter une présence / absence',
                new_transporter_absence_path(@transporter),
                class: 'btn-show'

  - if @absences.any?
    == pagy_nav(@pagy) if @pagy.pages > 1

    #absences
      = render collection: @absences, partial: 'transporters/absences/absence'

    == pagy_nav(@pagy) if @pagy.pages > 1

  - else
    .panel-info.mb-5
      | Il n'y a pas encore de présence ou absence de configurée


section.dark:text-white
  header.flex.flex-col.lg:flex-row.items-center.justify-between.mb-3.gap-3
    h2.text-xl Les horaires de travail

  - i18n_scope = 'activemodel'

  p
    strong Lundi:
    =< I18n.t(@transporter.availabilities.monday, scope: i18n_scope)

  p
    strong Mardi:
    =< I18n.t(@transporter.availabilities.tuesday, scope: i18n_scope)

  p
    strong Mercredi:
    =< I18n.t(@transporter.availabilities.wednesday, scope: i18n_scope)

  p
    strong Jeudi:
    =< I18n.t(@transporter.availabilities.thursday, scope: i18n_scope)

  p
    strong Vendredi:
    =< I18n.t(@transporter.availabilities.friday, scope: i18n_scope)

  p
    strong Samedi:
    =< I18n.t(@transporter.availabilities.saturday, scope: i18n_scope)

  p
    strong Dimanche:
    =< I18n.t(@transporter.availabilities.sunday, scope: i18n_scope)