config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#show'

  mount GoodJob::Engine => 'good_job'

  resource :sessions, only: %i[new create destroy]
  get '/sessions' => redirect('/sessions/new')

  resources :password_resets, only: %i[new create edit update]

  resource :settings, only: %i[edit update]
  resolve('Setting') { [:settings] }

  resource :companies, only: %i[new create edit update]
  resolve('Company') { [:companies] }

  resources :users, only: %i[new create]

  namespace :me do
    resource :profile, only: %i[show edit update]
  end

  resources :customers do
    member do
      delete :archive
    end

    collection do
      get :daily
    end
  end
  resources :vehicles

  resources :places do
    collection do
      get :daily
    end
  end

  resources :transporters do
    collection do
      get :daily
    end
    scope module: :transporters do
      resources :absences, except: %i[index show]
    end
  end

  resources :daily_quests, only: %i[index show destroy] do
    member do
      post :reset
      post :duplicate_week
      post 'optimize'
    end

    scope module: :daily_quests do
      resources :missions

      resources :steps, only: %i[edit update destroy] do
        member do
          post 'optimize'
        end
      end

      resources :transporters, only: [] do
        collection do
          post :send_all_plannings
        end

        member do
          post :send_planning
        end

        scope module: :transporters do
          resources :steps, only: %i[index]
        end
      end

      resources :missions, only: [] do
        scope module: :missions do
          resources :steps, only: %i[index update]
        end
      end
    end
  end

  namespace :addresses do
    resource :search, only: :show
  end
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  enum status: { normal: 0, breakdown: 1, mechanic: 2 }

  belongs_to :company
  has_one :transporter, dependent: :nullify

  has_one_attached :photo
  has_rich_text :details

  humanize :status, enum: true

  validates :name, presence: true
  validates :number_plate, presence: true, uniqueness: true
  validates :max_regular_seats, presence: true, numericality: { only_integer: true }
  validates :max_wheelchair_seats, presence: true, numericality: { only_integer: true }

  scope :enabled, -> { where(enabled: true) }

  after_create :assign_photo, unless: -> { photo.present? }
  before_update :unassign_transporter, if: :unavailable_vehicle?

  private

  def assign_photo
    url = "https://ui-avatars.com/api/?format=jpg&name=#{I18n.transliterate(name)}&size=256"

    photo.attach(io: URI.parse(url).open, filename: 'vehicle.jpg')
  end

  def unassign_transporter
    self.transporter = nil
  end

  def unavailable_vehicle?
    status_changed?(to: :breakdown) || status_changed?(to: :mechanic)
  end
end

# == Schema Information
#
# Table name: vehicles
#
#  id                   :bigint(8)        not null, primary key
#  name                 :string
#  number_plate         :string
#  width                :float
#  height               :float
#  length               :float
#  max_regular_seats    :integer          default(0), not null
#  max_wheelchair_seats :integer          default(0), not null
#  status               :integer          default("normal"), not null
#  substitution         :boolean          default(FALSE), not null
#  enabled              :boolean          default(TRUE), not null
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  company_id           :bigint(8)
#
# Indexes
#
#  index_vehicles_on_company_id    (company_id)
#  index_vehicles_on_number_plate  (number_plate) UNIQUE
#

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: %i[show edit update destroy]

  # @route GET /vehicles (vehicles)
  def index
    authorize! Vehicle

    vehicles = authorized_scope(company.vehicles)

    @pagy, @vehicles = pagy(vehicles)
  end

  # @route GET /vehicles/new (new_vehicle)
  def new
    authorize! Vehicle

    @vehicle = company.vehicles.new
  end

  # @route POST /vehicles (vehicles)
  def create
    authorize! Vehicle

    @vehicle = company.vehicles.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html do
          redirect_url = params[:mode] == 'save_and_create_new' ? new_vehicle_path : vehicle_path(@vehicle)
          redirect_to redirect_url, notice: 'Le véhicule a bien été créé.'
        end
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # @route GET /vehicles/:id (vehicle)
  def show
    authorize! @vehicle
  end

  # @route GET /vehicles/:id/edit (edit_vehicle)
  def edit
    authorize! @vehicle
  end

  # @route PATCH /vehicles/:id (vehicle)
  # @route PUT /vehicles/:id (vehicle)
  def update
    authorize! @vehicle

    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to vehicle_path(@vehicle), notice: 'Le véhicule a bien été mis à jour.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # @route DELETE /vehicles/:id (vehicle)
  def destroy
    authorize! @vehicle

    @vehicle.destroy

    respond_to do |format|
      format.html { redirect_to vehicles_path, notice: 'Le véhicule a bien été supprimé.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_vehicle
    @vehicle = company.vehicles.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def vehicle_params
    permitted_attributes = %i[
      name number_plate width height length enabled
      details max_wheelchair_seats max_regular_seats
      status substitution
    ]

    permitted_attributes.push(:photo) if options.enable_vehicle_photo?

    params.require(:vehicle).permit(permitted_attributes)
  end
end

app/views/vehicles/_form.html.slim
= simple_form_for(@vehicle) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  - if f.object.errors.any?
    ul.list-disc.list-inside.panel-error.mb-6
      - f.object.errors.full_messages.each do |message|
        li= message

  .flex.flex-col.lg:flex-row.justify-between.gap-3.mb-6
    = f.input :name, wrapper_html: { class: 'w-full' }
    = f.input :number_plate, wrapper_html: { class: 'w-full' }
    = f.input :status,
              collection: select_options_for(Vehicle, :statuses),
              include_blank: false,
              wrapper_html: { class: 'w-full' }

  .flex.flex-col.lg:flex-row.justify-between.gap-3.mb-6
    = f.input :length, wrapper_html: { class: 'w-full' }
    = f.input :width, wrapper_html: { class: 'w-full' }
    = f.input :height, wrapper_html: { class: 'w-full' }

  .flex.flex-col.lg:flex-row.justify-between.gap-3.mb-6
    = f.input :max_regular_seats, wrapper_html: { class: 'w-full' }
    = f.input :max_wheelchair_seats, wrapper_html: { class: 'w-full' }

  .flex.flex-col.lg:flex-row.justify-between.gap-3.mb-6
    = f.input :details, as: :rich_text_area,
              wrapper_html: { class: 'w-full' }

    - if options.enable_vehicle_photo?
      div
        = f.input :photo, as: :file

        - if f.object.photo.attached?
          p.mt-3.text-center= image_tag url_for(f.object.photo), class: 'w-32 rounded-full object-cover'

  = f.input :substitution, as: :boolean, wrapper_html: { class: 'mb-6' }
  = f.input :enabled, as: :boolean, wrapper_html: { class: 'mb-6' }

  .flex.items-center.gap-3
    = f.button :submit

    - if @vehicle.new_record?
      = f.button :button, 'Valider et créer un nouveau véhicule >>', type: :submit, name: :mode, value: 'save_and_create_new'

app/views/vehicles/_vehicle.html.slim
details.row id=dom_id(vehicle) class=('opacity-50' unless vehicle.enabled?)
  summary.flex.flex-col.lg:flex-row.items-center.gap-3.justify-between.p-2.relative
    .flex.items-center.gap-2
      - if vehicle.photo.attached?
        = image_tag url_for(vehicle.photo), class: 'w-16 h-16 rounded-full object-cover'
      div
        p.mb-1
          span.font-bold= vehicle.name
          span.italic.text-gray-500=< "(#{vehicle.number_plate})"
        - unless vehicle.normal?
          p.inline-block.mb-1.bg-orange-500.px-2.py-1.text-sm.rounded-lg.text-white= vehicle.human_status
        p.text-sm
          - if vehicle.transporter.present?
            = link_to transporter_path(vehicle.transporter), class: 'flex items-center gap-1' do
              - if vehicle.transporter.photo.attached?
                = image_tag vehicle.transporter.photo, class: 'w-6 h-6 object-cover rounded-full'
              = vehicle.transporter.full_name
          - elsif vehicle.normal?
            span.text-orange-500 ⚠️ Véhicule sans chauffeur

    .flex.items-center.gap-3
      - if allowed_to?(:show?, vehicle)
        = link_to 'Fiche véhicule', vehicle_path(vehicle), class: 'btn-show'
      - if allowed_to?(:update?, vehicle)
        = link_to 'Modifier', edit_vehicle_path(vehicle), class: 'btn-edit'
      - if allowed_to?(:destroy?, vehicle)
        = button_to 'Supprimer', vehicle,
                    class: 'btn-destroy',
                    method: :delete,
                    data: { turbo_confirm: 'Voulez-vous supprimer ce véhicule ?' }

  .p-2.border-t.dark:border-gray-600
    p
      strong Longueur:
      =< vehicle.width.presence || '/'
    p
      strong Hauteur:
      =< vehicle.height.presence || '/'

    p
      strong Nombre de places assises:
      =< vehicle.max_regular_seats

    p
      strong Nombre de places en fauteuil roulant:
      =< vehicle.max_wheelchair_seats

    p
      strong Status:
      =< vehicle.human_status

    p
      strong Véhicule de remplacement ?
      =< t(vehicle.substitution.to_s)

    = vehicle.details

app/views/vehicles/edit.html.slim
header.flex.flex-col.lg:flex-row.items-center.justify-between.mb-6.gap-3
  h1.text-3xl Modifier un véhicule

  - if allowed_to?(:update?, @vehicle)
    = link_to '<< Retour aux véhicules', vehicles_path, class: 'btn-back'

= render 'form', vehicle: @vehicle

app/views/vehicles/index.html.slim
header.flex.flex-col.lg:flex-row.items-center.justify-between.mb-6.gap-3
  h1.text-3xl Véhicules

  - if allowed_to?(:create?, Vehicle)
    = link_to 'Ajouter un véhicule', new_vehicle_path, class: 'btn-add'

- unless current_user.standard?
  details.panel-info.mb-5 open=options.show_help?
    summary.cursor-pointer Explications à lire

    p.mt-3 Les différents véhicules sont à renseigner sur cette page. Les véhicules peuvent ensuite être associés à un chauffeur.

- if @vehicles.any?
  == pagy_nav(@pagy) if @pagy.pages > 1

  #vehicles
    = render @vehicles

  == pagy_nav(@pagy) if @pagy.pages > 1

- else
  p.panel-warning.p-4
    | Il n'y a pas encore de véhicules -

    - if allowed_to?(:create?, Vehicle)
      =< link_to 'Ajouter le premier', new_vehicle_path, class: 'underline'

app/views/vehicles/new.html.slim
header.flex.flex-col.lg:flex-row.items-center.justify-between.mb-6.gap-3
  h1.text-3xl Ajouter un véhicule

  - if allowed_to?(:index?, Vehicle)
    = link_to '<< Retour aux véhicules', vehicles_path, class: 'btn-back'

= render 'form', vehicle: @vehicle

app/views/vehicles/show.html.slim
header.flex.flex-col.lg:flex-row.items-center.justify-between.mb-6.gap-3
  h1.text-3xl= @vehicle.name

  .flex.items-center.gap-2
    = link_to '<< Retour aux véhicules', vehicles_path, class: 'btn-back'

    - if allowed_to?(:update?, @vehicle)
      = link_to 'Modifier', edit_vehicle_path(@vehicle), class: 'btn-edit'

    - if allowed_to?(:destroy?, @vehicle)
      = button_to 'Supprimer', @vehicle,
                  class: 'btn-destroy',
                  method: :delete,
                  data: { turbo_confirm: 'Voulez-vous supprimer ce véhicule ?' }

.row.p-4 id=dom_id(@vehicle)
  - if @vehicle.photo.attached?
    p.mb-3= image_tag url_for(@vehicle.photo), class: 'max-w-[300px]'

  p
    strong Plaque d'immatriculation:
    =< @vehicle.number_plate

  p
    strong Longueur:
    =< @vehicle.width.presence || '/'

  p
    strong Hauteur:
    =< @vehicle.height.presence || '/'

  p
    strong Nombre de places assises:
    =< @vehicle.max_regular_seats

  p
    strong Nombre de places en fauteuil roulant:
    =< @vehicle.max_wheelchair_seats

  p
    strong Status:
    =< @vehicle.human_status

  p
    strong Véhicule de remplacement ?
    =< t(@vehicle.substitution.to_s)

  - if @vehicle.details?
    div
      p: strong Détails:
      = @vehicle.details